<a href="https://colab.research.google.com/github/GabrielJTorres/Python_aulas/blob/main/aula_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Criando NumPy Arrays

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##Métodos de Construção

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
np.arange(0,10,4)

array([0, 4, 8])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.linspace(0,10,51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##Random

In [ ]:
np.random.rand(3) #amostra aletória entre [0,1]

array([0.70845327, 0.46377876, 0.0422681 ])

In [ ]:
np.random.rand(5,5)

array([[0.04534573, 0.03369327, 0.3908384 , 0.95528678, 0.82322869],
       [0.23755912, 0.10839563, 0.64582789, 0.04267081, 0.88644397],
       [0.14536577, 0.05856704, 0.5347929 , 0.84844442, 0.15534542],
       [0.56165291, 0.40692277, 0.58994016, 0.67176345, 0.85850508],
       [0.71612956, 0.46860445, 0.32961394, 0.06189329, 0.9343528 ]])

In [ ]:
np.random.randn(3) #distribuição normal centrada em zero

array([ 1.33979628, -0.01027065,  2.16349634])

In [ ]:
np.random.randn(5,5)

array([[ 0.02206515,  0.29726663,  3.67573352, -0.38031247, -1.95411614],
       [-2.04180421, -0.01833234, -1.09938404,  0.83211856,  0.1350887 ],
       [ 1.783302  ,  1.18996953,  0.02440349, -0.07481542, -0.11571943],
       [ 2.6068798 ,  1.30930801, -0.68987031, -1.05006059, -0.5436525 ],
       [ 0.74062091,  0.36283699,  0.77290966, -1.35783877, -1.20257392]])

In [ ]:
np.random.randint(1,100) #número inteiro aleatório entre [1, 100)

79

In [ ]:
np.random.randint(1,100, 10)

array([86, 96,  8, 96, 45, 92, 22, 28, 11, 44])

##Atributos e Métodos

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([35, 30, 16, 24, 35,  8, 11, 25, 20,  0])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr.max()

33

In [ ]:
ranarr.argmax()

0

In [ ]:
ranarr.min()

1

In [ ]:
ranarr.argmin()

5

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5).shape

(5, 5)

In [ ]:
arr.dtype

dtype('int64')

#Indexação e Seleção

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[2:5]

array([2, 3, 4])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[5]

5

In [ ]:
arr[:5] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr = arr[0:5]

In [ ]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

##Indexando um array 2D (matrizes)

In [ ]:
#obs: o formato geral é arr_2d[row][col] ou arr_2d[row, col]
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[1]

array([20, 25, 30])

In [ ]:
arr_2d[1,0]

20

In [ ]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr_2d[:,2]

array([15, 30, 45])

#Indexação sofisticada (fancy indexing)

In [ ]:
arr2d = np.zeros((10,10))

arr_length = arr2d.shape[1]

for i in range(arr_length):
  arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
arr2d[[4,2,7,9]]

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

##Seleção

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x=3
arr[arr>x]

array([ 4,  5,  6,  7,  8,  9, 10])

#Operações no NumPy

##Aritmética

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])